### ISSUE TITLE
how to install ObjFIle?

### ISSUE THREAD

**Issue by donghaoye** [pclausen/obj2png#1]

**Comment by pclausen** [comment]
Sorry, but I do now understand the question. You can read about "Obj-file" here: [https://en.wikipedia.org/wiki/Wavefront_.obj_file](https://en.wikipedia.org/wiki/Wavefront_.obj_file ).
When you have such a file you can convert it to a png file with this little tool. To test, you can try it with obj2png/obj/bun_zipper_res2.obj from the repo.
