### ISSUE TITLE
Error when executing on Max OSX

### ISSUE THREAD

**Issue by agGitHub** [pclausen/obj2png#12]
Hi,

I am trying to use your tool on my Mac.

I installed python3.

Now I do:

`python3 obj2png.py -i bunny.obj -v`

I get the following errors:

```
Traceback (most recent call last):
  File "/Users/xxx/obj2png/obj2png-main/src/obj2png.py", line 32, in <module>
    import ObjFile
  File "/Users/xxx/obj2png/obj2png-main/src/ObjFile.py", line 32, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

In line 32 of your code in obj2png.py,  there is:
`import ObjFile`

How can I solve this problem? 

Thanks.

**Comment by agGitHub** [comment]
Ok, solved my problem. So install python3 from python website.

Then, once you have the error mentioned in my initial post:
`python3 -m pip install numpy`
and then:
`pip3.10 install matplotlib`

I am a newbie with python... 

Thanks for your great tool.

**Comment by pclausen** [comment]
great you found a solution! 😃
