### ISSUE TITLE
Does your tool support .mtl files associated with .obj files ?

### ISSUE THREAD

**Issue by agGitHub** [pclausen/obj2png#13]
Hello,

Before I try to use your great tool, I would like to know if it converts to png only the .obj file or also (.obj + .mtl) bundles ? And also (.obj + .mtl + .png) bundles (meaning .obj with textures)? 

Thanks.

**Comment by pclausen** [comment]
@agGitHub I dont think matplotlib supports .mtl or any textures. You may want to look for more advanced visualization tools.
