### ISSUE TITLE
Clipping

### ISSUE THREAD

**Issue by GenaAiv** [pclausen/obj2png#14]
Hi,
Not an issue but a question/request.

I searched the web and can't find the solution so I was hoping you could help.

I am transforming my obj to png but would like to have the possibility to clip/cut the object. Not sure what the right word for it is but here is an example:

My object .obj file looks like this:
![image](https://user-images.githubusercontent.com/65892609/197465339-6a18e7fc-7822-40cf-8354-05b9298f1093.png)

and comes out like this:
![image](https://user-images.githubusercontent.com/65892609/197465300-a5e68334-f662-41fc-ab77-49e31846428d.png)

Another way of seeing this would be:
I would want to move the camera in space, to get very close to the object, or better go through the object, and halfway in in it, where the other half is out of picture and clipped, i would want to create a .png of the current view.

Any idea how i could achieve that?

**Comment by pclausen** [comment]
@GenaAiv I do not know how to implement this. You may want to look into more capable visualization tools.
