### ISSUE TITLE
Rotation and translation of object

### ISSUE THREAD

**Issue by isuba** [pclausen/obj2png#2]
Hi, 
Great work, thanks.

Can we able to get the rotation and translation of the object as matrix?

Best regards, Suresh

**Comment by pclausen** [comment]
sorry, did not see this before. I dont know if matplotlib can write out the rotation matrix but it would be possible somehow.... 
maybe have a look at https://rock-learning.github.io/pytransform3d/rotations.html and see if that helps you ?
