### ISSUE TITLE
Still have a bug in ObjFile.py

### ISSUE THREAD

**Issue by Chenge321** [pclausen/obj2png#5]
Thanks for your work. And I still have met this problem after I download the latest version code. Could you fix it again?
PS D:\obj2png-master\src> python obj2png.py -i 2.obj
Namespace(animate=False, azim=None, elevation=None, objfiles=['2.obj'], outfile=None, quality=None, scale=None, view=False)
Converting 2.obj to 2.png
Traceback (most recent call last):
  File "obj2png.py", line 122, in <module>
    ob.Plot(outfile,elevation=elevation,azim=azim,dpi=dpi,scale=scale,animate=animate)
  File "D:\obj2png-master\src\ObjFile.py", line 178, in Plot
    ax.plot_trisurf(self.nodes[:,0],self.nodes[:,1],self.nodes[:,2], triangles=tri)
IndexError: too many indices for array
[2.zip](https://github.com/pclausen/obj2png/files/5577636/2.zip)

**Comment by pclausen** [comment]
@Chenge321 Thanks for reporting, now fixed
