### ISSUE TITLE
Obj file loaded with incorrect apsects and scale

### ISSUE THREAD

**Issue by ewassef** [pclausen/obj2png#7]
Hello, 

First of all, this is a fantastic script, thank you. 

I am noticing that the plotting of the obj is not the correct proportion. loading the attached file, I get 
![image](https://user-images.githubusercontent.com/5826918/104144221-fae60100-5387-11eb-8963-8d229f1d6295.png)
while opening it in windows gives me:
![image](https://user-images.githubusercontent.com/5826918/104144232-09341d00-5388-11eb-8079-6e3ca285d1ff.png)

I would also like to change the color from blue to something else, and I haven't figured out how to do that yet. 
Any help?

[car2.zip](https://github.com/pclausen/obj2png/files/5793862/car2.zip)

**Comment by ewassef** [comment]
@pclausen friendly ping in case youre not watching this repo closely

**Comment by YairShemer** [comment]
See [here](https://stackoverflow.com/questions/8130823/set-matplotlib-3d-plot-aspect-ratio) some solutions for this problem.  
As tfpf recommends there, in ObjFile.py (after line 194) add the lines:  
`limits = np.array([getattr(self.ax, f'get_{axis}lim')() for axis in 'xyz']) ;   
ax.set_box_aspect(np.ptp(limits, axis = 1))`  
It did the work for me.

**Comment by pclausen** [comment]
@ewassef sorry for taking so long to reply. Did @YairShemer suggestion help ?
